---
- name: "tasks for deploying devstack - system config"
  hosts: hosts
  gather_facts: no
  vars:
    - ansible_ssh_user: stack
  tasks:
    - name: set permission for horizon
      sudo: yes
      shell: >
        chmod 600 /opt/stack/horizon/openstack_dashboard/local/.secret_key_store

    - name: set stackrc file
      template:
        src: templates/stackrc.j2
        dest: '{{ devstack_user_home }}/stackrc'
        mode: 0755
